{
  "name": "equihub-api",
  "build": {
    "command": "cd server && npm install && npm run build"
  },
  "start": {
    "command": "cd server && npm start"
  },
  "healthcheck": {
    "path": "/",
    "timeout": 30
  }
}
